#=========
#数据库配置
#=========
spring:
  datasource:
    url: jdbc:mysql://59.110.237.203:3306/test?useUnicode:true&characterEncoding:UTF-8
    name: test
    username: admin
    password: Admin,123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 10000
      pool-prepared-statements: false
      #max-pool-prepared-statement-per-connection-size:
      #max-open-prepared-statements:
      validation-query: select 1 from dual
      validation-query-timeout: 10000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #time-between-eviction-runs-millis:60000
      #min-evictable-idle-time-millis:
      #max-evictable-idle-time-millis:
      #配置多个英文逗号分隔
      #filters:
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #是否启用StatFilter默认值true
      #web-stat-filter.enabled:
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions:
        -*.js
        -*.gif
        -*.jpg
        -*.png
        -*.css
        -*.ico
        -/druid/*
        -/druid
      #web-stat-filter.session-stat-enable:
      #web-stat-filter.session-stat-max-count:
      #web-stat-filter.principal-session-name:
      #web-stat-filter.principal-cookie-name:
      #web-stat-filter.profile-enable:
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #是否启用StatViewServlet默认值true
      #stat-view-servlet.enabled:
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      #stat-view-servlet.allow:
      #stat-view-servlet.deny:
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.redbean.distributor.service.*
      # 如果aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class:true